MutexDotCom/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MutexDotCom.Data;
using MutexDotCom.Data.Services.Abstract;
using MutexDotCom.Models;

namespace MutexDotCom.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DepartmentController : Controller
    {
        private readonly IDepartmentService _service;
        public DepartmentController(IDepartmentService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var data=await _service.GetAllAsync();
            return View(data);
        }
        //Get: Actors/Developer
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name,Logo,Description")] Department department)
        {
            if (ModelState.IsValid)
            {
                return View(department);
            }
            await _service.CreateAsync(department);
            return RedirectToAction("Index");
        }
        //Get: Departments/Details/id
        public async Task<IActionResult> Details(int id)
        {
            var devDetails = await _service.GetByIdAsync(id);

            if (devDetails == null) return View("NotFound");
            return View(devDetails);
        }

        //Get: Departments/Edit/id
        public async Task<IActionResult> Edit(int id)
        {
            var devDetails = await _service.GetByIdAsync(id);
            if (devDetails == null)
            {
                return View("NotFound");
            }
            return View(devDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Logo,Description")] Department department)
        {
            if (ModelState.IsValid)
            {
                return View(department);
            }
            await _service.UpdateAsync(id, department);
            return RedirectToAction(nameof(Index));
        }
        //Get: Department/Delete/id
        public async Task<IActionResult> Delete(int id)
        {
            var devDetails = await _service.GetByIdAsync(id);
            if (devDetails == null) return View("NotFound");
            return View(devDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var devDetails = await _service.GetByIdAsync(id);
            if (devDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

MutexDotCom/Controllers/DeveloperController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MutexDotCom.Data;
using MutexDotCom.Data.Services.Abstract;
using MutexDotCom.Models;

namespace MutexDotCom.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DeveloperController : Controller
    {
        private readonly IDeveloperService _service;
        public DeveloperController(IDeveloperService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var data=await _service.GetAllAsync();
            return View(data);
        }
        
        //Get: Actors/Developer
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name,ProfilePictureURL,Skills")] Developer developer)
        {
            if (ModelState.IsValid)
            {
                return View(developer);
            }
            await _service.CreateAsync(developer);
            return RedirectToAction("Index");
        }
        
        //Get: Developers/Details/id
        public async Task<IActionResult> Details(int id)
        {
            var devDetails = await _service.GetByIdAsync(id);

            if (devDetails == null) return View("NotFound");
            return View(devDetails);
        }

        //Get: Developers/Edit/id
        public async Task<IActionResult> Edit(int id)
        {
            var devDetails = await _service.GetByIdAsync(id);
            if (devDetails == null)
            {
                return View("NotFound");
            }
            return View(devDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,ProfilePictureURL,Skills")] Developer developer)
        {
            if (ModelState.IsValid)
            {
                return View(developer);
            }
            await _service.UpdateAsync(id, developer);
            return RedirectToAction(nameof(Index));
        }

        //Get: Developer/Delete/id
        public async Task<IActionResult> Delete(int id)
        {
            var devDetails = await _service.GetByIdAsync(id);
            if (devDetails == null) return View("NotFound");
            return View(devDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var devDetails = await _service.GetByIdAsync(id);
            if (devDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

MutexDotCom/Controllers/ManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MutexDotCom.Data;
using MutexDotCom.Data.Services.Abstract;
using MutexDotCom.Models;

namespace MutexDotCom.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ManagerController : Controller
    {
        private readonly IManagerService _service;
        public ManagerController(IManagerService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }
        //Get: Manager/create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name,ProfilePictureURL,Description")] Manager manager)
        {
            if (ModelState.IsValid)
            {
                return View(manager);
            }
            await _service.CreateAsync(manager);
            return RedirectToAction("Index");
        }
        //Get: Manager/Details/id
        public async Task<IActionResult> Details(int id)
        {
            var devDetails = await _service.GetByIdAsync(id);

            if (devDetails == null) return View("NotFound");
            return View(devDetails);
        }
        //Get: Manager/Edit/id
        public async Task<IActionResult> Edit(int id)
        {
            var devDetails = await _service.GetByIdAsync(id);
            if (devDetails == null)
            {
                return View("NotFound");
            }
            return View(devDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,ProfilePictureURL,Description")] Manager manager)
        {
            if (ModelState.IsValid)
            {
                return View(manager);
            }
            await _service.UpdateAsync(id, manager);
            return RedirectToAction(nameof(Index));
        }
        //Get: Manager/Delete/id
        public async Task<IActionResult> Delete(int id)
        {
            var devDetails = await _service.GetByIdAsync(id);
            if (devDetails == null) return View("NotFound");
            return View(devDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var devDetails = await _service.GetByIdAsync(id);
            if (devDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

MutexDotCom/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MutexDotCom.Data;
using MutexDotCom.Data.Services.Abstract;
using MutexDotCom.Data.ViewModels;

namespace MutexDotCom.Controllers
{
    public class ProjectController : Controller
    {
        private readonly IProjectService _service;
        public ProjectController(IProjectService service)
        {
            _service = service;  
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync(n=>n.Department);
            return View(data);
        }
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var data = await _service.GetProjectByIdAsync(id);
            return View(data);
        }
        
        //GET/Project/Create/id
        public async Task<IActionResult> Create()
        {
            var data = await _service.GetProjectServiceValues();

            ViewBag.Departmnets = new SelectList(data.Departments, "Id", "Name");
            ViewBag.Managers = new SelectList(data.Managers, "Id", "Name");
            ViewBag.Developers = new SelectList(data.Developers, "Id", "Name");

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(NewProjectVM project)
        {
            if(!ModelState.IsValid)
            {
                var data = await _service.GetProjectServiceValues();


                ViewBag.Departments = new SelectList(data.Departments, "Id", "Name");
                ViewBag.Managers = new SelectList(data.Managers, "Id", "Name");
                ViewBag.Developers = new SelectList(data.Developers, "Id", "Name");

                return View(project);
            }
            await _service.AddNewProjectAsync(project);
            return RedirectToAction(nameof(Index));
        }
        
        //GET/Project/Edit/id
        public async Task<IActionResult> Edit(int id)
        {
            var data= await _service.GetProjectByIdAsync(id);

            var res = new NewProjectVM()
            {
                Id = data.Id,
                Name = data.Name,
                ProbelemStatement = data.ProbelemStatement,
                ClientName = data.ClientName,
                ImageURL = data.ImageURL,
                InitialDate = data.InitialDate,
                EndDate = data.EndDate,
                DepartmentIds=data.DepartmentId,
                ManagerIds=data.ManagerId,
                DevelopersIds=data.DevProjects.Select(n=>n.DevId).ToList(),
            };

            var projectDD = await _service.GetProjectServiceValues();
            ViewBag.Departments = new SelectList(projectDD.Departments, "Id", "Name");
            ViewBag.Managers = new SelectList(projectDD.Managers, "Id", "Name");
            ViewBag.Developers = new SelectList(projectDD.Developers, "Id", "Name");
            return View(res);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewProjectVM project)
        {
            if (id != project.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var projectDD = await _service.GetProjectServiceValues();
                ViewBag.Departments = new SelectList(projectDD.Departments, "Id", "Name");
                ViewBag.Managers = new SelectList(projectDD.Managers, "Id", "Name");
                ViewBag.Developers = new SelectList(projectDD.Developers, "Id", "Name");

                return View(project);
            }
            await _service.UpdateProjectAsync(project);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Filter(string searchString)
        {
            var data = await _service.GetAllAsync(n => n.Department);

            if (!string.IsNullOrEmpty(searchString))
            {
                var filterRes = data.Where(n => string.Equals(n.Name, searchString, StringComparison.CurrentCultureIgnoreCase) || string.Equals(n.ProbelemStatement, searchString, StringComparison.CurrentCultureIgnoreCase)).ToList();
                return View("Index", filterRes);
            }

            return View("Index", data);
        }

    }
}

MutexDotCom/Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">You've reached the end of the internet</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Project" asp-action="Index">Home Page</a>
    </div>
</div>

MutexDotCom/Views/Shared/_CreateItemPartial.cshtml
@model string;


@if (User.IsInRole("Admin")) 
{

    <div style="position: fixed; right: 25px; bottom: 25px;" class="text-white">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
            <i class="bi bi-plus-circle"></i> Add New
        </a>
    </div>
}

MutexDotCom/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MutexDotCom</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MutexDotCom.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Movies" asp-action="Index">MutexDotCon</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Index"><i class="bi bi-film"></i> Project</a>
                        </li>

                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {


                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Management
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Department" asp-action="Index"><i class="bi bi-camera-reels"></i> Departments</a>
                                    <a class="dropdown-item" asp-controller="Manager" asp-action="Index"><i class="bi bi-headset"></i> Managers</a>
                                    <a class="dropdown-item" asp-controller="Developer" asp-action="Index"><i class="bi bi-person-square"></i> Developers</a>
                                </div>
                            </li>
                        }

                    </ul>

                    <form class="form-inline my-2 my-lg-0" asp-controller="Project" asp-action="Filter" style="padding-right: 25px;">
                        <div class="input-group">
                            <input name="searchString" type="text" class="form-control" placeholder="Search the project..." aria-label="Recipient's username" aria-describedby="button-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-outline-success" type="submit"><i class="bi bi-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <partial name="_LoginPartial"/>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MutexDotCom - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>